# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/lightdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/lightdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/lightdb/CMakeFiles /root/lightdb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/lightdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyProject

# Build rule for target.
MyProject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyProject
.PHONY : MyProject

# fast build rule for target.
MyProject/fast:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/build
.PHONY : MyProject/fast

db_hash.o: db_hash.cpp.o
.PHONY : db_hash.o

# target to build an object file
db_hash.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_hash.cpp.o
.PHONY : db_hash.cpp.o

db_hash.i: db_hash.cpp.i
.PHONY : db_hash.i

# target to preprocess a source file
db_hash.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_hash.cpp.i
.PHONY : db_hash.cpp.i

db_hash.s: db_hash.cpp.s
.PHONY : db_hash.s

# target to generate assembly for a file
db_hash.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_hash.cpp.s
.PHONY : db_hash.cpp.s

db_list.o: db_list.cpp.o
.PHONY : db_list.o

# target to build an object file
db_list.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_list.cpp.o
.PHONY : db_list.cpp.o

db_list.i: db_list.cpp.i
.PHONY : db_list.i

# target to preprocess a source file
db_list.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_list.cpp.i
.PHONY : db_list.cpp.i

db_list.s: db_list.cpp.s
.PHONY : db_list.s

# target to generate assembly for a file
db_list.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_list.cpp.s
.PHONY : db_list.cpp.s

db_set.o: db_set.cpp.o
.PHONY : db_set.o

# target to build an object file
db_set.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_set.cpp.o
.PHONY : db_set.cpp.o

db_set.i: db_set.cpp.i
.PHONY : db_set.i

# target to preprocess a source file
db_set.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_set.cpp.i
.PHONY : db_set.cpp.i

db_set.s: db_set.cpp.s
.PHONY : db_set.s

# target to generate assembly for a file
db_set.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_set.cpp.s
.PHONY : db_set.cpp.s

db_str.o: db_str.cpp.o
.PHONY : db_str.o

# target to build an object file
db_str.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_str.cpp.o
.PHONY : db_str.cpp.o

db_str.i: db_str.cpp.i
.PHONY : db_str.i

# target to preprocess a source file
db_str.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_str.cpp.i
.PHONY : db_str.cpp.i

db_str.s: db_str.cpp.s
.PHONY : db_str.s

# target to generate assembly for a file
db_str.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_str.cpp.s
.PHONY : db_str.cpp.s

db_zset.o: db_zset.cpp.o
.PHONY : db_zset.o

# target to build an object file
db_zset.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_zset.cpp.o
.PHONY : db_zset.cpp.o

db_zset.i: db_zset.cpp.i
.PHONY : db_zset.i

# target to preprocess a source file
db_zset.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_zset.cpp.i
.PHONY : db_zset.cpp.i

db_zset.s: db_zset.cpp.s
.PHONY : db_zset.s

# target to generate assembly for a file
db_zset.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/db_zset.cpp.s
.PHONY : db_zset.cpp.s

dump.o: dump.cpp.o
.PHONY : dump.o

# target to build an object file
dump.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/dump.cpp.o
.PHONY : dump.cpp.o

dump.i: dump.cpp.i
.PHONY : dump.i

# target to preprocess a source file
dump.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/dump.cpp.i
.PHONY : dump.cpp.i

dump.s: dump.cpp.s
.PHONY : dump.s

# target to generate assembly for a file
dump.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/dump.cpp.s
.PHONY : dump.cpp.s

idx.o: idx.cpp.o
.PHONY : idx.o

# target to build an object file
idx.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/idx.cpp.o
.PHONY : idx.cpp.o

idx.i: idx.cpp.i
.PHONY : idx.i

# target to preprocess a source file
idx.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/idx.cpp.i
.PHONY : idx.cpp.i

idx.s: idx.cpp.s
.PHONY : idx.s

# target to generate assembly for a file
idx.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/idx.cpp.s
.PHONY : idx.cpp.s

lightdb.o: lightdb.cpp.o
.PHONY : lightdb.o

# target to build an object file
lightdb.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/lightdb.cpp.o
.PHONY : lightdb.cpp.o

lightdb.i: lightdb.cpp.i
.PHONY : lightdb.i

# target to preprocess a source file
lightdb.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/lightdb.cpp.i
.PHONY : lightdb.cpp.i

lightdb.s: lightdb.cpp.s
.PHONY : lightdb.s

# target to generate assembly for a file
lightdb.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/lightdb.cpp.s
.PHONY : lightdb.cpp.s

server/cmd/LightdbRequestHandler.o: server/cmd/LightdbRequestHandler.cpp.o
.PHONY : server/cmd/LightdbRequestHandler.o

# target to build an object file
server/cmd/LightdbRequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/LightdbRequestHandler.cpp.o
.PHONY : server/cmd/LightdbRequestHandler.cpp.o

server/cmd/LightdbRequestHandler.i: server/cmd/LightdbRequestHandler.cpp.i
.PHONY : server/cmd/LightdbRequestHandler.i

# target to preprocess a source file
server/cmd/LightdbRequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/LightdbRequestHandler.cpp.i
.PHONY : server/cmd/LightdbRequestHandler.cpp.i

server/cmd/LightdbRequestHandler.s: server/cmd/LightdbRequestHandler.cpp.s
.PHONY : server/cmd/LightdbRequestHandler.s

# target to generate assembly for a file
server/cmd/LightdbRequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/LightdbRequestHandler.cpp.s
.PHONY : server/cmd/LightdbRequestHandler.cpp.s

server/cmd/cmd.o: server/cmd/cmd.cpp.o
.PHONY : server/cmd/cmd.o

# target to build an object file
server/cmd/cmd.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd.cpp.o
.PHONY : server/cmd/cmd.cpp.o

server/cmd/cmd.i: server/cmd/cmd.cpp.i
.PHONY : server/cmd/cmd.i

# target to preprocess a source file
server/cmd/cmd.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd.cpp.i
.PHONY : server/cmd/cmd.cpp.i

server/cmd/cmd.s: server/cmd/cmd.cpp.s
.PHONY : server/cmd/cmd.s

# target to generate assembly for a file
server/cmd/cmd.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd.cpp.s
.PHONY : server/cmd/cmd.cpp.s

server/cmd/cmd_hash.o: server/cmd/cmd_hash.cpp.o
.PHONY : server/cmd/cmd_hash.o

# target to build an object file
server/cmd/cmd_hash.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_hash.cpp.o
.PHONY : server/cmd/cmd_hash.cpp.o

server/cmd/cmd_hash.i: server/cmd/cmd_hash.cpp.i
.PHONY : server/cmd/cmd_hash.i

# target to preprocess a source file
server/cmd/cmd_hash.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_hash.cpp.i
.PHONY : server/cmd/cmd_hash.cpp.i

server/cmd/cmd_hash.s: server/cmd/cmd_hash.cpp.s
.PHONY : server/cmd/cmd_hash.s

# target to generate assembly for a file
server/cmd/cmd_hash.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_hash.cpp.s
.PHONY : server/cmd/cmd_hash.cpp.s

server/cmd/cmd_list.o: server/cmd/cmd_list.cpp.o
.PHONY : server/cmd/cmd_list.o

# target to build an object file
server/cmd/cmd_list.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_list.cpp.o
.PHONY : server/cmd/cmd_list.cpp.o

server/cmd/cmd_list.i: server/cmd/cmd_list.cpp.i
.PHONY : server/cmd/cmd_list.i

# target to preprocess a source file
server/cmd/cmd_list.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_list.cpp.i
.PHONY : server/cmd/cmd_list.cpp.i

server/cmd/cmd_list.s: server/cmd/cmd_list.cpp.s
.PHONY : server/cmd/cmd_list.s

# target to generate assembly for a file
server/cmd/cmd_list.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_list.cpp.s
.PHONY : server/cmd/cmd_list.cpp.s

server/cmd/cmd_set.o: server/cmd/cmd_set.cpp.o
.PHONY : server/cmd/cmd_set.o

# target to build an object file
server/cmd/cmd_set.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_set.cpp.o
.PHONY : server/cmd/cmd_set.cpp.o

server/cmd/cmd_set.i: server/cmd/cmd_set.cpp.i
.PHONY : server/cmd/cmd_set.i

# target to preprocess a source file
server/cmd/cmd_set.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_set.cpp.i
.PHONY : server/cmd/cmd_set.cpp.i

server/cmd/cmd_set.s: server/cmd/cmd_set.cpp.s
.PHONY : server/cmd/cmd_set.s

# target to generate assembly for a file
server/cmd/cmd_set.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_set.cpp.s
.PHONY : server/cmd/cmd_set.cpp.s

server/cmd/cmd_str.o: server/cmd/cmd_str.cpp.o
.PHONY : server/cmd/cmd_str.o

# target to build an object file
server/cmd/cmd_str.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_str.cpp.o
.PHONY : server/cmd/cmd_str.cpp.o

server/cmd/cmd_str.i: server/cmd/cmd_str.cpp.i
.PHONY : server/cmd/cmd_str.i

# target to preprocess a source file
server/cmd/cmd_str.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_str.cpp.i
.PHONY : server/cmd/cmd_str.cpp.i

server/cmd/cmd_str.s: server/cmd/cmd_str.cpp.s
.PHONY : server/cmd/cmd_str.s

# target to generate assembly for a file
server/cmd/cmd_str.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_str.cpp.s
.PHONY : server/cmd/cmd_str.cpp.s

server/cmd/cmd_zset.o: server/cmd/cmd_zset.cpp.o
.PHONY : server/cmd/cmd_zset.o

# target to build an object file
server/cmd/cmd_zset.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_zset.cpp.o
.PHONY : server/cmd/cmd_zset.cpp.o

server/cmd/cmd_zset.i: server/cmd/cmd_zset.cpp.i
.PHONY : server/cmd/cmd_zset.i

# target to preprocess a source file
server/cmd/cmd_zset.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_zset.cpp.i
.PHONY : server/cmd/cmd_zset.cpp.i

server/cmd/cmd_zset.s: server/cmd/cmd_zset.cpp.s
.PHONY : server/cmd/cmd_zset.s

# target to generate assembly for a file
server/cmd/cmd_zset.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/cmd/cmd_zset.cpp.s
.PHONY : server/cmd/cmd_zset.cpp.s

server/epoll.o: server/epoll.cpp.o
.PHONY : server/epoll.o

# target to build an object file
server/epoll.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/epoll.cpp.o
.PHONY : server/epoll.cpp.o

server/epoll.i: server/epoll.cpp.i
.PHONY : server/epoll.i

# target to preprocess a source file
server/epoll.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/epoll.cpp.i
.PHONY : server/epoll.cpp.i

server/epoll.s: server/epoll.cpp.s
.PHONY : server/epoll.s

# target to generate assembly for a file
server/epoll.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/epoll.cpp.s
.PHONY : server/epoll.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

storage/db_file.o: storage/db_file.cpp.o
.PHONY : storage/db_file.o

# target to build an object file
storage/db_file.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/storage/db_file.cpp.o
.PHONY : storage/db_file.cpp.o

storage/db_file.i: storage/db_file.cpp.i
.PHONY : storage/db_file.i

# target to preprocess a source file
storage/db_file.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/storage/db_file.cpp.i
.PHONY : storage/db_file.cpp.i

storage/db_file.s: storage/db_file.cpp.s
.PHONY : storage/db_file.s

# target to generate assembly for a file
storage/db_file.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/storage/db_file.cpp.s
.PHONY : storage/db_file.cpp.s

util/sync/CTimer.o: util/sync/CTimer.cpp.o
.PHONY : util/sync/CTimer.o

# target to build an object file
util/sync/CTimer.cpp.o:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/util/sync/CTimer.cpp.o
.PHONY : util/sync/CTimer.cpp.o

util/sync/CTimer.i: util/sync/CTimer.cpp.i
.PHONY : util/sync/CTimer.i

# target to preprocess a source file
util/sync/CTimer.cpp.i:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/util/sync/CTimer.cpp.i
.PHONY : util/sync/CTimer.cpp.i

util/sync/CTimer.s: util/sync/CTimer.cpp.s
.PHONY : util/sync/CTimer.s

# target to generate assembly for a file
util/sync/CTimer.cpp.s:
	$(MAKE) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/util/sync/CTimer.cpp.s
.PHONY : util/sync/CTimer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MyProject"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... db_hash.o"
	@echo "... db_hash.i"
	@echo "... db_hash.s"
	@echo "... db_list.o"
	@echo "... db_list.i"
	@echo "... db_list.s"
	@echo "... db_set.o"
	@echo "... db_set.i"
	@echo "... db_set.s"
	@echo "... db_str.o"
	@echo "... db_str.i"
	@echo "... db_str.s"
	@echo "... db_zset.o"
	@echo "... db_zset.i"
	@echo "... db_zset.s"
	@echo "... dump.o"
	@echo "... dump.i"
	@echo "... dump.s"
	@echo "... idx.o"
	@echo "... idx.i"
	@echo "... idx.s"
	@echo "... lightdb.o"
	@echo "... lightdb.i"
	@echo "... lightdb.s"
	@echo "... server/cmd/LightdbRequestHandler.o"
	@echo "... server/cmd/LightdbRequestHandler.i"
	@echo "... server/cmd/LightdbRequestHandler.s"
	@echo "... server/cmd/cmd.o"
	@echo "... server/cmd/cmd.i"
	@echo "... server/cmd/cmd.s"
	@echo "... server/cmd/cmd_hash.o"
	@echo "... server/cmd/cmd_hash.i"
	@echo "... server/cmd/cmd_hash.s"
	@echo "... server/cmd/cmd_list.o"
	@echo "... server/cmd/cmd_list.i"
	@echo "... server/cmd/cmd_list.s"
	@echo "... server/cmd/cmd_set.o"
	@echo "... server/cmd/cmd_set.i"
	@echo "... server/cmd/cmd_set.s"
	@echo "... server/cmd/cmd_str.o"
	@echo "... server/cmd/cmd_str.i"
	@echo "... server/cmd/cmd_str.s"
	@echo "... server/cmd/cmd_zset.o"
	@echo "... server/cmd/cmd_zset.i"
	@echo "... server/cmd/cmd_zset.s"
	@echo "... server/epoll.o"
	@echo "... server/epoll.i"
	@echo "... server/epoll.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... storage/db_file.o"
	@echo "... storage/db_file.i"
	@echo "... storage/db_file.s"
	@echo "... util/sync/CTimer.o"
	@echo "... util/sync/CTimer.i"
	@echo "... util/sync/CTimer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

